In [1]:
import pandas as pd
import numpy as np
from sklearn.metrics.pairwise import euclidean_distances

damds_point_file = "/Users/bfeng/DSC-SPIDAL/applications/fungi-gene-sequence/scripts/damds/damds-points.txt.formatted"
damds_df = pd.read_csv(damds_point_file, usecols=[1, 2, 3], header=None, delim_whitespace=True)

In [2]:
mds_dist_df = euclidean_distances(damds_df, damds_df)

In [3]:
print(mds_dist_df)

[[0.         0.34883726 0.13100556 ... 0.25881718 0.15927275 0.2266322 ]
 [0.34883726 0.         0.41445106 ... 0.45214879 0.32489953 0.3344058 ]
 [0.13100556 0.41445106 0.         ... 0.19097046 0.25774926 0.19519921]
 ...
 [0.25881718 0.45214879 0.19097046 ... 0.         0.2784405  0.12129331]
 [0.15927275 0.32489953 0.25774926 ... 0.2784405  0.         0.23505564]
 [0.2266322  0.3344058  0.19519921 ... 0.12129331 0.23505564 0.        ]]


In [6]:
out_df = pd.DataFrame(mds_dist_df)
out_df.to_csv("/Users/bfeng/DSC-SPIDAL/applications/fungi-gene-sequence/scripts/damds/mds_distance.csv", header=False, index=False)